defmodule VistorManagement.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      modify :is_admin, :boolean, null: true, default: false
    end
  end

  def down do
    alter table(:users) do
      modify :is_admin, :boolean, null: false, default: nil
    end
  end
end
