defmodule VistorManagement.Repo.Migrations.AddNewAttributeToResource2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tickets) do
      add :create_date, :utc_datetime
      add :update_date, :utc_datetime
    end
  end

  def down do
    alter table(:tickets) do
      remove :update_date
      remove :create_date
    end
  end
end
