defmodule VistorManagement.Repo.Migrations.MigrateResources3 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tickets) do
      modify :follower, :bigint, null: false, default: 0
      modify :visit_end_date, :utc_datetime, null: false
      modify :visit_start_date, :utc_datetime, null: false
      add :uid, :text, null: false
      add :visit_reason, :text, null: false
    end
  end

  def down do
    alter table(:tickets) do
      remove :visit_reason
      remove :uid
      modify :visit_start_date, :utc_datetime, null: true
      modify :visit_end_date, :utc_datetime, null: true
      modify :follower, :bigint, null: true, default: nil
    end
  end
end
